### PR TITLE
Fixes for 15 and 16

### PR DESCRIPTION
**Pull request by dploeger**
Sorry for not disecting the changes here, but I started with a fix for #16, then #15 and finally noticed, that the whitespace format for the file was mixed so I converted it all to spaces.

So this includes configuring the ImageMagick binary path (which I needed on macOS) #15, the support for stereoscopy/multiviews #16.

### CODE REVIEW

**Comment by DreadKnight** [comment]
Thanks for the PR.


Anyone around with a mac to test this out? Otherwise I'll merge eventually after a test on linux (just in case).

**Comment by dploeger** [comment]
I added another commit that fixes #18 as well.

**Comment by dploeger** [comment]
And it fixes #19 now as well.

@DreadKnight care to merge? ;-)

**Comment by DreadKnight** [comment]
Skimmed the code, will merge untested as I've been out of blender for a minute, really need to get back in soon.
Will probably convert it all to tabs, but in a different commit, as it will fully make this one muddy if doing so atm.

**Comment by dploeger** [comment]
Awesome, thanks.

**Comment by DreadKnight** [comment]
@dploeger Thanks again for your contributions :-) Can't wait to make good use of this add-on myself.

**Comment by dploeger** [comment]
yw. I'm already using it heavily for this game: https://gitlab.com/d1314/safehouse/safehouse-design :)

**Comment by DreadKnight** [comment]
@dploeger Hmm, interesting. Looking forward to some screenies or anything visual xD

**Comment by dploeger** [comment]
@DreadKnight Oh, I tweet about it from time to time using the account https://twitter.com/deepentertains

Here's an example of the first room of the game: https://twitter.com/deepentertains/status/1425828793919234070?s=20

**Pull request merged**
